$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json

type: pipeline
name: mushrooms-classification-v18
display_name: mushrooms Classification-v18
experiment_name: classification

inputs:
  train_test_split_factor: 20
  epochs: 5

outputs:
  model:
    type: uri_folder

settings:
  # default_compute: serverless
  default_compute: azureml:mlopsfinal

jobs:
  data_prep_agaricus:
    type: command
    component: ../components/dataprep/dataprep.yaml
    inputs:
      data:
        type: uri_folder
        path: azureml:agaricus:1
    outputs:
      output_data:
        mode: rw_mount

  data_prep_amanita:
    type: command
    component: ../components/dataprep/dataprep.yaml
    inputs:
      data:
        type: uri_folder
        path: azureml:amanita:1
    outputs:
      output_data:
        mode: rw_mount

  data_prep_boletus:
    type: command
    component: ../components/dataprep/dataprep.yaml
    inputs:
      data:
        type: uri_folder
        path: azureml:boletus:1
    outputs:
      output_data:
        mode: rw_mount

  data_prep_cortinarius:
    type: command
    component: ../components/dataprep/dataprep.yaml
    inputs:
      data:
        type: uri_folder
        path: azureml:cortinarius:1
    outputs:
      output_data:
        mode: rw_mount

  data_prep_entoloma:
    type: command
    component: ../components/dataprep/dataprep.yaml
    inputs:
      data:
        type: uri_folder
        path: azureml:entoloma:1
    outputs:
      output_data:
        mode: rw_mount

  data_prep_hygrocybe:
    type: command
    component: ../components/dataprep/dataprep.yaml
    inputs:
      data:
        type: uri_folder
        path: azureml:hygrocybe:1
    outputs:
      output_data:
        mode: rw_mount

  data_prep_lactarius:
    type: command
    component: ../components/dataprep/dataprep.yaml
    inputs:
      data:
        type: uri_folder
        path: azureml:lactarius:1
    outputs:
      output_data:
        mode: rw_mount

  data_prep_russula:
    type: command
    component: ../components/dataprep/dataprep.yaml
    inputs:
      data:
        type: uri_folder
        path: azureml:russula:1
    outputs:
      output_data:
        mode: rw_mount

  data_prep_suillus:
    type: command
    component: ../components/dataprep/dataprep.yaml
    inputs:
      data:
        type: uri_folder
        path: azureml:suillus:1
    outputs:
      output_data:
        mode: rw_mount

  data_split:
    type: command
    component: ../components/dataprep/data_split.yaml
    inputs:
      mushroom_1: ${{parent.jobs.data_prep_agaricus.outputs.output_data}}
      mushroom_2: ${{parent.jobs.data_prep_amanita.outputs.output_data}}
      mushroom_3: ${{parent.jobs.data_prep_boletus.outputs.output_data}}
      mushroom_4: ${{parent.jobs.data_prep_cortinarius.outputs.output_data}}
      mushroom_5: ${{parent.jobs.data_prep_entoloma.outputs.output_data}}
      mushroom_6: ${{parent.jobs.data_prep_hygrocybe.outputs.output_data}}
      mushroom_7: ${{parent.jobs.data_prep_lactarius.outputs.output_data}}
      mushroom_8: ${{parent.jobs.data_prep_russula.outputs.output_data}}
      mushroom_9: ${{parent.jobs.data_prep_suillus.outputs.output_data}}
      train_test_split_factor: ${{parent.inputs.train_test_split_factor}}
    outputs:
      testing_data:
        mode: rw_mount
      training_data:
        mode: rw_mount

  training:
    type: command
    component: ../components/training/training.yaml
    inputs:
      training_folder: ${{parent.jobs.data_split.outputs.training_data}}
      testing_folder: ${{parent.jobs.data_split.outputs.testing_data}}
      epochs: ${{parent.inputs.epochs}}
    outputs:
      output_folder:
        mode: rw_mount

  register:
    type: command
    component: azureml://registries/azureml/components/register_model/versions/0.0.9
    inputs:
      model_name: mushroom-classification
      model_type: custom_model
      model_path: ${{parent.jobs.training.outputs.output_folder}}
    outputs:
      registration_details_folder: ${{ parent.outputs.model }}
