apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/driessenslucas/mlops-mushrooms-api:latest
          env:
            - name: MONGODB_USERNAME
              value: 'root'
            - name: MONGODB_PASSWORD
              value: 'example'
            - name: MONGODB_HOSTNAME
              value: 'mongodb-service'
            - name: MONGODB_PORT
              value: '27017'
            - name: MONGODB_DATABASE
              value: 'mushrooms'
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: '1Gi'
              cpu: '500m'
            limits:
              memory: '4Gi'
              cpu: '2'
