version: '3'
services:
  api-1:
    ports:
      - 8001:8000
    # build:
    #   context: .
    #   platforms:
    #     - linux/arm64
    image: ghcr.io/driessenslucas/mlops-mushrooms-api:latest

  api-2:
    ports:
      - 8002:8000
    # build:
    #   context: .
    #   platforms:
    #     - linux/arm64
    image: ghcr.io/driessenslucas/mlops-mushrooms-api:latest

  # frontend:
  #   build: ./web
