version: '3'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
  api-1:
    ports:
      - 8001:8000
    # build:
    #   context: .
    #   platforms:
    #     - linux/arm64
    image: ghcr.io/driessenslucas/mlops-mushrooms-api:latest

  api-2:
    ports:
      - 8002:8000
    # build:
    #   context: .
    #   platforms:
    #     - linux/arm64
    image: ghcr.io/driessenslucas/mlops-mushrooms-api:latest

volumes:
  mongodb_data:
