name: Azure ML Automated Pushing pipeline

on:
  push:
    branches:
      - main

jobs:
  start:
    uses: ./.github/workflows/azure-ai.yaml
    with:
      # Set these to "true" if you want to run these pipeline steps or "false" to skip it
      create_compute: false
      create_cluster: false
      train_model: false
      skip_training_pipeline: true #default is false, true skips this step
      download_model: false
      deploy_model: false
      deploy_kubernetes: false

    secrets: inherit
