# Use an official Nginx runtime as the base image
FROM nginx:latest

# Copy your website files to the container
COPY ./ ./

# Expose the HTTP port
EXPOSE 8500

# Start Nginx when the container runs
CMD ["nginx", "-g", "daemon off;"]